Fix issue #158 (Access to providers and writers)
tinylog-org/tinylog pull request #161
Opened 2020-08-18 21:02 UTC by Git5000

Allow access to writer and provider #158  fixed.

Compared to the previous pull request this version follows now the Tinylog style checks. 

The getWriters(TAG, LEVEL) is not implemented as it seems of too little use.

Also the issue with the Exception vs ERROR in the test did not occur. Maybe a wrong configuration. So the test is like before. But maybe check whether it shouild be an Exception or an error string in case I got it wrong.

2020-08-18 21:20 UTC, pmwmedia requested changes
Thank you :) Looks very great 👍 Just a few minors to fix.

2020-08-18 21:20 UTC, pmwmedia commented on tinylog-api/src/main/java/org/tinylog/provider/ProviderRegistry.java
> +	 * Get all loaded logging providers.
Gets ...

2020-08-18 21:20 UTC, pmwmedia commented on tinylog-api/src/test/java/org/tinylog/provider/ProviderRegistryTest.java
> +
Please remove this empty line

2020-08-18 21:20 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/core/TinylogLoggingProvider.java
> +	 */
Formatting plus typo corrections:

```
	 * Gets all writers of the provider which respond to the given tag. A null tag is possible for the generic writer.
	 * 
	 * @param tag
	 *            The tag to find
	 * @return All writers
```

2020-08-18 21:20 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/core/TinylogLoggingProvider.java
> +	 */
Formatting plus typo corrections:

```
	 * Gets all writers of the provider.
	 * 
	 * @return All writers
```

2020-08-19 09:44 UTC, pmwmedia approved these changes

2020-08-19 10:02 UTC, pmwmedia commented
@Git5000 Thank you very much! Looks perfect :-)

Your Posteo email address that you used for your commits isn't linked to your GitHub account. Could you add it (https://github.com/settings/emails)? Afterwards, I'm gong to merge your pull requests. Without adding your email address to your GitHub account, GitHub won't increase the contributor count for tinylog. However, GitHub won't display your email address on your profile site, but these metrics are important for online media press for accepting articles about tinylog for publishing.

2020-08-19 10:02 UTC, pmwmedia approved these changes

2020-08-19 10:24 UTC, Git5000 commented
Thank you for the review. Is there any other action from me required?

2020-08-19 10:46 UTC, pmwmedia commented
@Git5000 Just add the email address to your GitHUb account (https://github.com/settings/emails) and your done :-)

2020-08-19 11:44 UTC, Git5000 commented
This posteo email is actually added to the Github account. But the settings is set to _private_ to prevent spam. Github says it replaces it by Git5000@users.noreply.github.com. Probably one should have used Git5000@users.noreply.github.com for the commits.
Is it necessary to make the original email public? It doesnt matter to me if it increased counts or not. (and sorry I am not veryexperienced with Github).

2020-08-19 12:17 UTC, pmwmedia commented
It should work also with private email addresses. There is no need to make the email address public.

2020-08-19 12:18 UTC, merged