RfC: Allow to dynamically change log filename using {logFile} segment
tinylog-org/tinylog pull request #230
Opened 2021-12-20 19:38 UTC by simon04

This is a draft meant for discussion

### Description

Allow to dynamically change log filename. Say you have a task consisting of the steps foo, bar, baz, and you'd like to obtain log files `foo.log`, `bar.log`, `baz.log`

This PR would allow to:

```java
Configuration.set("writer.file", "logs/{logFile}.log");
Configuration.set("writer.policies", "log file reset");
LogFileResetPolicy.setLogFile("foo");
runFoo(); // logs are written to logs/foo.log
LogFileResetPolicy.setLogFile("bar");
runBar(); // logs are written to logs/bar.log
LogFileResetPolicy.setLogFile("baz");
runBaz(); // logs are written to logs/baz.log
```

Would you be willing to support this feature? Is this draft implementation a feasible way to accomplish the goal? Is there a more concise way?

### Definition of Done

- [ ] I read [contributing.md](https://github.com/tinylog-org/tinylog/blob/v2.4/contributing.md)
- [ ] There are no TODOs left in the code
- [ ] Code style follows the tinylog standard
- [ ] All classes and methods have Javadoc
- [ ] Changes are covered by JUnit tests including edge cases, errors, and exception handling
- [ ] Maven build works including compiling, tests, and checks (`mvn verify`)
- [ ] Changes are committed by a verified email address that is assigned to the GitHub account (https://github.com/settings/emails)

### Documentation

Additions or amendments for the [public documentation](https://github.com/tinylog-org/tinylog/wiki/Documentation):

```markdown

```

### Agreements

- [x] I agree that my changes will be published under the terms of the [Apache License 2.0](https://github.com/tinylog-org/tinylog/blob/v2.0/license.txt) (mandatory)
- [x] I agree that my GitHub user name will be published in the release notes (optional)

2021-12-20 20:48 UTC, pmwmedia commented
Thank you for your pull request, and yes, I'm willing o support this feature.

Improvement suggestions:

- Fix the code style
- Support an initial log name as parameter aka  `log file reset: my-log-file`
- `LogFileResetPolicy` does not need to be based on `DailyPolicy` (if you need both, you can configure it on runtime via `daily, log file reset`)
- I'm not completely happy with the names `LogFileResetPolicy` and `LogFileSegment`, but I don't know a better name by now

2021-12-20 22:52 UTC, simon04 commented
> * Fix the code style

Done.
 
> * Support an initial log name as parameter aka  `log file reset: my-log-file`

Done.

> * `LogFileResetPolicy` does not need to be based on `DailyPolicy` (if you need both, you can configure it on runtime via `daily, log file reset`)

Very nice!

> * I'm not completely happy with the names `LogFileResetPolicy` and `LogFileSegment`, but I don't know a better name by now

Me neither. I also dislike the cross dependency between the two classes. Is there a better way? Should one class implement both interfaces?

Related (and more elaborated) concepts in other logging libraries are:
- http://logback.qos.ch/manual/appenders.html#SiftingAppender
- https://logging.apache.org/log4j/2.x/manual/appenders.html#RoutingAppender

2021-12-21 07:28 UTC, pmwmedia commented
You can fix the build by adding a bug pattern for `ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD` for `org.tinylog.policies.LogFileResetPolicy` into `configuration/spotbugs-filters.xml`.

2021-12-21 19:46 UTC, pmwmedia commented
Some thoughts and suggestions:

- The actual log name could be stored in `LogFileSegment` instead of `LogFileResetPolicy`. This will make the `LogFileResetPolicy` a bit more complex, but allows to use the `LogFileSegment` without having a `LogFileResetPolicy`.
- Currently, my favorite naming would be `DynamicNameSegment` and `DynamicNamePolicy`. However, other ideas are welcome :)
- I have just noticed that JUnit tests for `LogFileResetPolicy` are missing.
- I thought about merging the segment and policy to a single class. However, I think having separate classes are better readable and maintainable.

2021-12-21 21:07 UTC, pmwmedia commented
The release build fails because Java 6 does not support ` java.util.Objects.equals()`.

2021-12-21 23:07 UTC, pmwmedia requested changes
The code looks perfect! I found only a view Javadoc issues.

2021-12-21 23:07 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/path/DynamicNameSegment.java
> + * Path segment that represents the log filename from {@link DynamicNamePolicy}.
I assume this description is outdated ;-)

2021-12-21 23:07 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/path/DynamicNameSegment.java
> +	 * a {@linkplain Policy#reset() reset} is triggered.
Please place the `<p>` tags around the second paragraph

2021-12-21 23:07 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/path/DynamicNameSegment.java
> +	 * @return the current dynamic name
Javadoc should always start with a upper case letter in tinylog

2021-12-21 23:07 UTC, pmwmedia commented on tinylog-impl/src/main/java/org/tinylog/path/DynamicNameSegment.java
> +	 * @param newDynamicName the dynamic name to set
Javadoc should always start with a upper case letter in tinylog

2021-12-21 23:07 UTC, pmwmedia commented on tinylog-impl/src/test/java/org/tinylog/policies/DynamicNamePolicyTest.java
> +	 * Verifies that policy is registered as service under the name "startup".
Copy & paste mistake ;-)

2021-12-21 23:36 UTC, pmwmedia approved these changes

2021-12-21 23:37 UTC, pmwmedia commented
Thank you for your changes. It looks perfectly for me :)

2021-12-21 23:50 UTC, simon04 commented
Thank you for your patient and constructive reviews!

Sorry for a few glitches in Java 6 compatibility – I'm no longer used to write code targetting Java 6...

2021-12-22 06:32 UTC, merged